apiVersion: v1
kind: ServiceAccount
metadata:
  name: ddns
  namespace: ddns
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-ddns
  namespace: ddns
spec:
  provider:
    vault:
      server: http://vault.default.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: ddns
          serviceAccountRef:
            name: ddns
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ddns-secrets
  namespace: ddns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-ddns
    kind: SecretStore
  target:
    name: ddns-secrets
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef: { key: cert-manager/route53, property: access_key_id }
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef: { key: cert-manager/route53, property: secret_access_key }
    - secretKey: HOSTED_ZONE_ID
      remoteRef: { key: cert-manager/route53, property: hosted_zone_id }
    - secretKey: NTFY_TOKEN
      remoteRef: { key: ntfy/config, property: grafana_token }
